### ISSUE TITLE
why turn left is -direction.X

### ISSUE THREAD

**Issue by shaojunda** [nathany/get-programming-with-go#9]
https://github.com/nathany/get-programming-with-go/blob/master/lesson31/rover/rover.go#L58

the current position is (5,0), the current direction is (1, 0), According to the formula provided in the code after the left current direction to become to (0,-1). the current position becomes to (5, -1). Does this seem to turn right?

**Comment by nathany** [comment]
@rogpeppe would you like to answer this one? (it's from quite a while ago)

**Comment by rogpeppe** [comment]
This seems correct to me if we assume a y axis that increases from top to bottom. For this explanation, assume that going North decreases y; going East increases x.

If we're at (5, 0) with direction (1, 0), the previous position would have been (4, 0) (we're travelling East).

After turning left, the current direction becomes, (y, -x) which is (0, -1) as you say. This means that our new direction is North, which I'm pretty sure is turning left.
